# docker-compose.yml
version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - OMEJDN_DOMAIN=__HOST__
      - OMEJDN_PATH=/auth
      - UI_PATH=/
    volumes:
      - ./nginx.development.conf:/etc/nginx/nginx.conf:ro
      - __CERTDIRECTORY__:/etc/cert:ro
    networks:
      - local
    depends_on:
      - broker-core
      - broker-fuseki
      - omejdn-server
      - omejdn-ui
      - provide-connector
      - consume-connector

  broker-core:
    image: ghcr.io/data-space-core/dsil-idsa-broker/core:latest
    container_name: broker-core
    restart: always
    expose:
      - "8080"
    environment:
      - IDENTITY_JAVAKEYSTORE=/etc/cert/isstbroker-keystore.jks
      - SPARQL_ENDPOINT=http://broker-fuseki:3030/connectorData
      - ELASTICSEARCH_HOSTNAME=broker-elasticsearch
      - SHACL_VALIDATION=true
      - DAPS_VALIDATE_INCOMING=true
      - COMPONENT_URI=https://__HOST__/broker/
      - COMPONENT_CATALOGURI=https://__HOST__/broker/connectors/
      - JWKS_TRUSTEDHOSTS=__HOST__,daps
      - DAPS_URL=https://__HOST__/auth
      - DAPS_JWKS_URL=https://__HOST__/auth/jwks.json
    volumes:
      - __CERTDIRECTORY__:/etc/cert:ro
    networks:
      - local

  broker-fuseki:
    image: ghcr.io/data-space-core/dsil-idsa-broker/fuseki:latest
    container_name: broker-fuseki
    restart: always
    expose:
      - "3030"
    volumes:
      - broker-fuseki:/fuseki
    networks:
      - local

  omejdn-server:
    image: ghcr.io/data-space-core/dsil-omejdn-server/omejdn-server:latest
    container_name: daps
    hostname: daps
    restart: unless-stopped
    expose:
      - "4567"
    environment:
      - OMEJDN_ISSUER=https://__HOST__/auth
      - OMEJDN_FRONT_URL=https://__HOST__/auth
      - OMEJDN_OPENID=true
      - OMEJDN_ENVIRONMENT=${OMEJDN_ENVIRONMENT}
      - OMEJDN_ACCEPT_AUDIENCE=idsc:IDS_CONNECTORS_ALL
      - OMEJDN_DEFAULT_AUDIENCE=idsc:IDS_CONNECTORS_ALL
      - OMEJDN_ADMIN=${ADMIN_USERNAME}:${ADMIN_PASSWORD}
    volumes:
      - ./config:/opt/config
      - ./keys:/opt/keys
    networks:
      - local

  omejdn-ui:
    image: ghcr.io/fraunhofer-aisec/omejdn-ui:${UI_VERSION}
    container_name: omejdn-ui
    restart: unless-stopped
    expose:
      - "80"
    environment:
      - OIDC_ISSUER=https://__HOST__/auth/
      - API_URL=https://__HOST__/auth/api/v1
      - CLIENT_ID=adminUI
    networks:
      - local

  provide-connector-database:
    image: postgres:13
    container_name: provide-connector-database
    restart: unless-stopped
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgresuserb
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=connectorbdb
    volumes:
      - provide-connector-database:/var/lib/postgresql/data
    networks:
      - local

  provide-connector:
    image: ghcr.io/data-space-core/connector/stage:latest
    container_name: provide-connector
    restart: unless-stopped
    expose:
      - "8081"
    depends_on:
      - provide-connector-database
    environment:
      - CONFIGURATION_PATH=/config/config.json
      - SERVER_PORT=8081
      - DAPS_URL=https://__HOST__/auth
      - DAPS_TOKEN_URL=https://__HOST__/auth/token
      - DAPS_KEY_URL=https://__HOST__/auth/jwks.json
      - DAPS_INCOMING_DAT_DEFAULT_WELLKNOWN=/jwks.json
      - SERVER_SSLv_KEY-STORE=file:///conf/default-connector-keystore.p12
      - SPRING_DATASOURCE_URL=jdbc:postgresql://provide-connector-database:5432/connectorbdb
      - SPRING_DATASOURCE_USERNAME=postgresuserb
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_PLATFORM=postgres
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
    volumes:
      - ./conf/config.json:/config/config.json
      - ./conf/default-connector-keystore.p12:/conf/default-connector-keystore.p12
      - ./conf/truststore.p12:/config/truststore.p12
    networks:
      - local

  consume-connector-database:
    image: postgres:13
    container_name: consume-connector-database
    restart: unless-stopped
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgresuserb
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=connectorbdb
    volumes:
      - consume-connector-database:/var/lib/postgresql/data
    networks:
      - local

  consume-connector:
    image: ghcr.io/data-space-core/connector/stage:latest
    container_name: consume-connector
    restart: unless-stopped
    expose:
      - "8081"
    depends_on:
      - consume-connector-database
    environment:
      - CONFIGURATION_PATH=/config/config.json
      - SERVER_PORT=8081
      - DAPS_URL=https://__HOST__/auth
      - DAPS_TOKEN_URL=https://__HOST__/auth/token
      - DAPS_KEY_URL=https://__HOST__/auth/jwks.json
      - DAPS_INCOMING_DAT_DEFAULT_WELLKNOWN=/jwks.json
      - SERVER_SSLv_KEY-STORE=file:///conf/default-connector-keystore.p12
      - SPRING_DATASOURCE_URL=jdbc:postgresql://consume-connector-database:5432/connectorbdb
      - SPRING_DATASOURCE_USERNAME=postgresuserb
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_PLATFORM=postgres
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
    volumes:
      - ./conf/config.json:/config/config.json
      - ./conf/default-connector-keystore.p12:/conf/default-connector-keystore.p12
      - ./conf/truststore.p12:/config/truststore.p12
    networks:
      - local

volumes:
  broker-fuseki:
  provide-connector-database:
  consume-connector-database:

networks:
  local:
    driver: bridge
