services:
  # Nginx Reverse Proxy for handling HTTP and HTTPS traffic
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"   # Exposes HTTP on port 80
      - "443:443" # Exposes HTTPS on port 443
    env_file:
      - .env
    volumes:
      - ./.generated/nginx.conf:/etc/nginx/nginx.conf:ro # Generated Nginx configuration
      - ./cert:/etc/cert/:ro # SSL certificates
    networks:
      - local
    depends_on:
      - broker-core
      - broker-fuseki
      - omejdn-server
      - omejdn-ui
      - connector
      - connector-database

  # Broker Core Service - Manages data connectors and catalog
  broker-core:
    image: ghcr.io/data-space-core/dsil-idsa-broker/core:latest
    container_name: broker
    volumes:
      - /etc/cert:/etc/cert/ # SSL certificates
    restart: always
    environment:
      - IDENTITY_JAVAKEYSTORE=/etc/cert/isstbroker-keystore.jks
      - SPARQL_ENDPOINT=http://broker-fuseki:3030/connectorData # Use container name for Fuseki
      - ELASTICSEARCH_HOSTNAME=broker-elasticsearch
      - SHACL_VALIDATION=true
      - DAPS_VALIDATE_INCOMING=true
      - COMPONENT_URI=https://${DOMAIN}/broker/
      - COMPONENT_CATALOGURI=https://${DOMAIN}/broker/connectors/
      - JWKS_TRUSTEDHOSTS=${DOMAIN},daps
      - DAPS_URL=https://${DOMAIN}${OMEJDN_PATH}
      - DAPS_JWKS_URL=https://${DOMAIN}${OMEJDN_PATH}/jwks.json
    expose:
      - "8080" # Internal communication on port 8080
    networks:
      - local

  # Fuseki Service - Provides SPARQL endpoint for Broker Core
  broker-fuseki:
    image: ghcr.io/data-space-core/dsil-idsa-broker/fuseki:latest
    volumes:
      - broker-fuseki:/fuseki
    expose:
      - "3030" # Internal SPARQL communication on port 3030
    networks:
      - local

  # Omejdn Server - Handles OAuth2 and OpenID authentication
  omejdn-server:
    image: ghcr.io/data-space-core/dsil-omejdn-server/omejdn-server:latest
    container_name: daps
    hostname: daps
    restart: unless-stopped
    environment:
      - OMEJDN_ISSUER=https://${DOMAIN}${OMEJDN_PATH}
      - OMEJDN_FRONT_URL=https://${DOMAIN}${OMEJDN_PATH}
      - OMEJDN_OPENID=true
      - OMEJDN_ENVIRONMENT=${OMEJDN_ENVIRONMENT}
      - OMEJDN_ACCEPT_AUDIENCE=idsc:IDS_CONNECTORS_ALL
      - OMEJDN_DEFAULT_AUDIENCE=idsc:IDS_CONNECTORS_ALL
      - OMEJDN_ADMIN=${ADMIN_USERNAME}:${ADMIN_PASSWORD}
      - DAPS_VALIDATE_INCOMING=false
    volumes:
      - ./.generated/config:/opt/config
      - ./keys:/opt/keys # Keys and configurations
    networks:
      - local

  # Omejdn UI - Provides a user interface for managing Omejdn
  omejdn-ui:
    image: ghcr.io/fraunhofer-aisec/omejdn-ui:${UI_VERSION}
    restart: unless-stopped
    environment:
      - OIDC_ISSUER=https://${DOMAIN}${OMEJDN_PATH}/
      - API_URL=https://${DOMAIN}${OMEJDN_PATH}/api/v1
      - CLIENT_ID=adminUI
    networks:
      - local

  # Connector Database - PostgreSQL for Connector
  connector-database:
    image: postgres:13
    container_name: connector-database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - connector-database:/var/lib/postgresql/data # Data persistence
    networks:
      - local

  # Connector - Manages data provisioning with integration to PostgreSQL
  connector:
    image: ghcr.io/data-space-core/connector/stage:latest
    container_name: connector
    environment:
      - CONFIGURATION_PATH=/config/config.json
      - SERVER_PORT=8081
      - DAPS_URL=https://${DOMAIN}${OMEJDN_PATH}
      - DAPS_TOKEN_URL=https://${DOMAIN}${OMEJDN_PATH}/token
      - DAPS_KEY_URL=https://${DOMAIN}${OMEJDN_PATH}/jwks.json
      - DAPS_INCOMING_DAT_DEFAULT_WELLKNOWN=/jwks.json
      - SERVER_SSLv_KEY-STORE=file:///conf/default-connector-keystore.p12
      - SPRING_DATASOURCE_URL=jdbc:postgresql://connector-database:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATASOURCE_PLATFORM=postgres
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
    volumes:
      - ./.generated/config.json:/config/config.json:ro
      - ./conf/default-connector-keystore.p12:/conf/default-connector-keystore.p12
      - ./conf/truststore.p12:/config/truststore.p12
    networks:
      - local
    depends_on:
      - connector-database

  connector-registration:
    build:
      context: ./connector_registration
      dockerfile: Dockerfile
    container_name: connector-registration
    restart: unless-stopped
    volumes:
      - ./connector_registration:/app  # Mount the app directory for development
      - ./scripts:/scripts  # Map the scripts directory
      - ./keys:/keys  # Map the keys directory
      - ./.generated/config:/config  # Map the generated configuration directory
      - ./upload:/uploads  # Upload storage
    networks:
      - local
    depends_on:
      - connector

  connector-registration-user-interface:
    image: ghcr.io/data-space-core/connector-registration/stage:latest
    container_name: connector-registration-user-interface
    restart: unless-stopped
    # Access via Nginx path /connector-registration-user-interface/
    environment:
      - DJANGO_SECRET_KEY=your-secret-key-here
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_DB_ENGINE=django.db.backends.sqlite3
      - DJANGO_DB_NAME=db.sqlite3
      - DJANGO_LANGUAGE_CODE=en-us
      - DJANGO_TIME_ZONE=UTC
      - BASE_URL=https://digi4live.collab-cloud.eu/connector-registration/register-connector
    networks:
      - local

  provider-ui:
    container_name: provider-ui
    image: ghcr.io/data-space-core/provide-user-interface/stage:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .env:/app/.env
    # Access via Nginx path /provider-ui/
    networks:
      - local
  
  consumer-ui:
    container_name: consumer-ui
    image: ghcr.io/data-space-core/consume-user-interface-2/stage:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .env:/app/.env
    # Access via Nginx path /consume/
    networks:
      - local
  
volumes:
  broker-fuseki: # Volume for Fuseki data
  connector-database: # Volume for Connector data

networks:
  local:
    driver: bridge # Bridge network for inter-service communication
