- client_id: 24:23:13:AE:C8:C2:A0:79:0D:A1:F2:2F:21:A3:68:C9:B8:A9:0D:C9:24:23:13:AE:C8:C2:A0:79:0D:A1:F2:2F:21:A3:68:C9:B8:A9:0D:C9
  client_name: BOOO
  grant_types: client_credentials
  token_endpoint_auth_method: private_key_jwt
  scope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
  - key: idsc
    value: IDS_CONNECTOR_ATTRIBUTES_ALL
  - key: securityProfile
    value: BASE_SECURITY_PROFILE
  - key: referringConnector
    value: http://BOOO.demo
  - key: "@type"
    value: ids:DatPayload
  - key: "@context"
    value: https://w3id.org/idsa/contexts/context.jsonld
  - key: transportCertsSha256
    value: 17c387d302d18f1a0fe81fc236cadc18a204416250e381477fa371591a725cc3
- client_id: 24:23:13:AE:C8:C2:A0:79:0D:A1:F2:2F:21:A3:68:C9:B8:A9:0D:C9:keyid:24:23:13:AE:C8:C2:A0:79:0D:A1:F2:2F:21:A3:68:C9:B8:A9:0D:C9
  client_name: BOOO22
  grant_types: client_credentials
  token_endpoint_auth_method: private_key_jwt
  scope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
  - key: idsc
    value: IDS_CONNECTOR_ATTRIBUTES_ALL
  - key: securityProfile
    value: BASE_SECURITY_PROFILE
  - key: referringConnector
    value: http://BOOO22.demo
  - key: "@type"
    value: ids:DatPayload
  - key: "@context"
    value: https://w3id.org/idsa/contexts/context.jsonld
  - key: transportCertsSha256
    value: 17c387d302d18f1a0fe81fc236cadc18a204416250e381477fa371591a725cc3
- client_id: 24:23:13:AE:C8:C2:A0:79:0D:A1:F2:2F:21:A3:68:C9:B8:A9:0D:C9:keyid:24:23:13:AE:C8:C2:A0:79:0D:A1:F2:2F:21:A3:68:C9:B8:A9:0D:C9
  client_name: BOOO33
  grant_types: client_credentials
  token_endpoint_auth_method: private_key_jwt
  scope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
  - key: idsc
    value: IDS_CONNECTOR_ATTRIBUTES_ALL
  - key: securityProfile
    value: BASE_SECURITY_PROFILE
  - key: referringConnector
    value: http://BOOO33.demo
  - key: "@type"
    value: ids:DatPayload
  - key: "@context"
    value: https://w3id.org/idsa/contexts/context.jsonld
  - key: transportCertsSha256
    value: 17c387d302d18f1a0fe81fc236cadc18a204416250e381477fa371591a725cc3
- client_id: 7D:A7:B7:0D:4F:4B:58:E5:C0:DB:E3:0D:00:84:FE:91:6F:98:10:20:keyid:8D:8C:5E:C4:54:AD:8A:E1:77:E9:9B:F9:9B:05:E1:B8:01:8D:61:E1
  client_name: BOOO
  grant_types: client_credentials
  token_endpoint_auth_method: private_key_jwt
  scope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
  - key: idsc
    value: IDS_CONNECTOR_ATTRIBUTES_ALL
  - key: securityProfile
    value: BASE_SECURITY_PROFILE
  - key: referringConnector
    value: http://BOOO.demo
  - key: "@type"
    value: ids:DatPayload
  - key: "@context"
    value: https://w3id.org/idsa/contexts/context.jsonld
  - key: transportCertsSha256
    value: f934ee3281fbb376bdf002ff335d41552303f9b5a588eea77a0a99b7bc94eadb
- client_id: 7D:A7:B7:0D:4F:4B:58:E5:C0:DB:E3:0D:00:84:FE:91:6F:98:10:20:keyid:8D:8C:5E:C4:54:AD:8A:E1:77:E9:9B:F9:9B:05:E1:B8:01:8D:61:E1
  client_name: default-connector
  grant_types: client_credentials
  token_endpoint_auth_method: private_key_jwt
  scope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
  - key: idsc
    value: IDS_CONNECTOR_ATTRIBUTES_ALL
  - key: securityProfile
    value: BASE_SECURITY_PROFILE
  - key: referringConnector
    value: http://default-connector.demo
  - key: "@type"
    value: ids:DatPayload
  - key: "@context"
    value: https://w3id.org/idsa/contexts/context.jsonld
  - key: transportCertsSha256
    value: f934ee3281fbb376bdf002ff335d41552303f9b5a588eea77a0a99b7bc94eadb
- client_id: 7D:A7:B7:0D:4F:4B:58:E5:C0:DB:E3:0D:00:84:FE:91:6F:98:10:20:keyid:8D:8C:5E:C4:54:AD:8A:E1:77:E9:9B:F9:9B:05:E1:B8:01:8D:61:E1
  client_name: default-connector
  grant_types: client_credentials
  token_endpoint_auth_method: private_key_jwt
  scope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
  - key: idsc
    value: IDS_CONNECTOR_ATTRIBUTES_ALL
  - key: securityProfile
    value: BASE_SECURITY_PROFILE
  - key: referringConnector
    value: http://default-connector.demo
  - key: "@type"
    value: ids:DatPayload
  - key: "@context"
    value: https://w3id.org/idsa/contexts/context.jsonld
  - key: transportCertsSha256
    value: f934ee3281fbb376bdf002ff335d41552303f9b5a588eea77a0a99b7bc94eadb
- client_id: 7D:A7:B7:0D:4F:4B:58:E5:C0:DB:E3:0D:00:84:FE:91:6F:98:10:20:keyid:8D:8C:5E:C4:54:AD:8A:E1:77:E9:9B:F9:9B:05:E1:B8:01:8D:61:E1
  client_name: default-connector
  grant_types: client_credentials
  token_endpoint_auth_method: private_key_jwt
  scope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
  - key: idsc
    value: IDS_CONNECTOR_ATTRIBUTES_ALL
  - key: securityProfile
    value: BASE_SECURITY_PROFILE
  - key: referringConnector
    value: http://default-connector.demo
  - key: "@type"
    value: ids:DatPayload
  - key: "@context"
    value: https://w3id.org/idsa/contexts/context.jsonld
  - key: transportCertsSha256
    value: f934ee3281fbb376bdf002ff335d41552303f9b5a588eea77a0a99b7bc94eadb
- client_id: 7D:A7:B7:0D:4F:4B:58:E5:C0:DB:E3:0D:00:84:FE:91:6F:98:10:20:keyid:8D:8C:5E:C4:54:AD:8A:E1:77:E9:9B:F9:9B:05:E1:B8:01:8D:61:E1
  client_name: default-connector
  grant_types: client_credentials
  token_endpoint_auth_method: private_key_jwt
  scope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
  - key: idsc
    value: IDS_CONNECTOR_ATTRIBUTES_ALL
  - key: securityProfile
    value: BASE_SECURITY_PROFILE
  - key: referringConnector
    value: http://default-connector.demo
  - key: "@type"
    value: ids:DatPayload
  - key: "@context"
    value: https://w3id.org/idsa/contexts/context.jsonld
  - key: transportCertsSha256
    value: f934ee3281fbb376bdf002ff335d41552303f9b5a588eea77a0a99b7bc94eadb
- client_id: 7D:A7:B7:0D:4F:4B:58:E5:C0:DB:E3:0D:00:84:FE:91:6F:98:10:20:keyid:8D:8C:5E:C4:54:AD:8A:E1:77:E9:9B:F9:9B:05:E1:B8:01:8D:61:E1
  client_name: default-connector
  grant_types: client_credentials
  token_endpoint_auth_method: private_key_jwt
  scope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
  - key: idsc
    value: IDS_CONNECTOR_ATTRIBUTES_ALL
  - key: securityProfile
    value: BASE_SECURITY_PROFILE
  - key: referringConnector
    value: http://default-connector.demo
  - key: "@type"
    value: ids:DatPayload
  - key: "@context"
    value: https://w3id.org/idsa/contexts/context.jsonld
  - key: transportCertsSha256
    value: f934ee3281fbb376bdf002ff335d41552303f9b5a588eea77a0a99b7bc94eadb
