name: compose-validate
on:
  push:
  pull_request:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Docker Compose
        uses: docker/setup-buildx-action@v3
      - name: docker compose config
        run: docker compose config

